trigger:
  - main

pool:
  name: COMP367-Windows

stages:
  - stage: Prepare
    displayName: 'Preparation Stage'
    jobs:
      - job: CheckoutAndSetup
        displayName: 'Checkout and Setup Environment'
        steps:
        
        - checkout: self
          displayName: 'Checkout Repository'

        - task: NodeTool@0
          inputs:
            versionSpec: '20.12.2'
          displayName: 'Install Node.js'

        - task: Cache@2
          inputs:
            key: 'npm | "$(Agent.OS)" | package-lock.json'
            restoreKeys: 'npm | "$(Agent.OS)"'
            path: $(Build.SourcesDirectory)/node_modules
          displayName: 'Cache node_modules'

  - stage: BuildAndTest
    displayName: 'Build and Test Stage'
    jobs:
      - job: Build
        displayName: 'Build Application'
        steps:
        - script: |
            echo "Installing dependencies..."
            npm install
            echo "Compiling application using build tool (npm)..."
            npm run build
          displayName: 'Compile Project'

        - script: |
            echo "Running unit tests and generating code coverage report..."
            npm run test --coverage
          displayName: 'Unit Tests and Code Coverage'

  - stage: Analyze
    displayName: 'Code Analysis Stage'
    jobs:
      - job: SonarQubeAnalysis
        displayName: 'SonarQube Analysis'
        steps:

        - task: SonarQubePrepare@5
          inputs:
            SonarQube: 'SonarQube-community'
            scannerMode: 'CLI'
            configMode: 'file'
            extraProperties: |
              sonar.projectKey=DevOps-Implementation-FrontEnd

        - task: SonarQubeAnalyze@5
          inputs:
            jdkversion: 'JAVA_HOME_17_X64'

        - task: SonarQubePublish@5
          inputs:
            pollingTimeoutSec: '300'

  - stage: Deliver
    displayName: 'Deliver Artifact Stage'
    jobs:
      - job: DeliverArtifact
        displayName: 'Deliver Artifact'
        steps:
          - script: |
              echo "Packaging application..."
              npm run package
            displayName: 'Package Application'
