trigger:
  - dev

variables:
  - group: PAT

pool:
  name: COMP367-Windows

stages:
  - stage: Prepare
    displayName: 'Preparation Stage'
    jobs:
      - job: CheckoutAndSetup
        displayName: 'Checkout and Setup Environment'
        steps:
        - script: |
            echo "Using PAT stored"
            git clone https://shield0225:$(myGitHubPAT)@github.com/shield0225/G7-HealthTracker
          displayName: 'Clone private repository'

        - task: NodeTool@0
          inputs:
            versionSpec: '20.12.2'
          displayName: 'Install Node.js'

        - script: |
            if not exist "$(Build.SourcesDirectory)\node_modules" mkdir "$(Build.SourcesDirectory)\node_modules"
          displayName: 'Ensure node_modules directory exists'
          condition: succeeded()

        - task: Cache@2
          inputs:
            key: 'npm | "$(Agent.OS)" | package-lock.json'
            restoreKeys: 'npm | "$(Agent.OS)"'
            path: $(Build.SourcesDirectory)/node_modules
          displayName: 'Cache node_modules'

  - stage: BuildAndTest
    displayName: 'Build and Test Stage'
    jobs:
      - job: Build
        displayName: 'Build Application'
        steps:
        - script: |
            npm install
            npm run build
          displayName: 'Install Dependencies and Build'

      - job: Test
        displayName: 'Run Tests'
        steps:
        - script: |
            npm run lint
            npm test
            npm run coverage
          displayName: 'Lint, Test, and Generate Coverage'

  - stage: Analyze
    displayName: 'Code Analysis Stage'
    jobs:
      - job: SonarQubeAnalysis
        displayName: 'SonarQube Analysis'
        steps:
        - task: SonarQubePrepare@5
          inputs:
            SonarQube: 'SonarQube'
            scannerMode: 'Other'
            extraProperties: |
              sonar.projectKey=DevOps-Implementation-FrontEnd_DevOps-Implementation-FrontEnd_b070fab6-e6fd-485f-879c-646018c07ae6
              sonar.projectName=DevOps-Implementation-FrontEnd
              sonar.sources=src
              sonar.exclusions=**/*.test.js,**/node_modules/**
              sonar.tests=src
              sonar.test.inclusions=**/*.test.js
              sonar.javascript.lcov.reportPaths=coverage/lcov.info

        - task: SonarQubeAnalyze@5
          inputs:
            jdkversion: 'JAVA_HOME_17_X64'

        - task: SonarQubePublish@5
          inputs:
            pollingTimeoutSec: '300'
          env:
            SYSTEM_DEBUG: true

  - stage: Publish
    displayName: 'Publish Artifacts'
    jobs:
      - job: PublishArtifacts
        displayName: 'Publish Build Artifacts'
        steps:
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.SourcesDirectory)/build'
            ArtifactName: 'build'
            publishLocation: 'Container'
